<?php

namespace Database\Seeders;

use App\Models\Armateur;
use App\Models\Banque;
use App\Models\Client;
use App\Models\Representant;
use App\Models\Transitaire;
use Illuminate\Database\Seeder;

class DemoDataSeeder extends Seeder
{
    public function run(): void
    {
        // Banques (colonnes: nom, numero_compte, rib, iban, swift, solde, actif)
        Banque::create([
            'nom' => 'BGFI Bank',
            'numero_compte' => '0001-0000-0001',
            'rib' => 'BGFI001',
            'iban' => 'GA21 4000 0000 0000 0000 0000 001',
            'swift' => 'BGFIGAXX',
            'solde' => 15000000,
            'actif' => true,
        ]);

        Banque::create([
            'nom' => 'UGB Banque',
            'numero_compte' => '0002-0000-0001',
            'rib' => 'UGB001',
            'iban' => 'GA21 4000 0000 0000 0000 0000 002',
            'swift' => 'UGBAGAXX',
            'solde' => 5000000,
            'actif' => true,
        ]);

        // Clients importés depuis la base legacy (~400 clients)
        $clients = [
            ['nom' => 'COMPLEXE HOTELERIE LE TRAIT D UNION', 'email' => 'Letrait@logistiga.com', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'ETS ADEMONLA ET FILS', 'email' => 'Fils@logistiga.com', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'LAME SERVICE SRL', 'email' => 'Lame@logistiga.com', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'CENTR\' AFFAIRE DISTRIBUTION', 'email' => 'contact@centr-affaires.com', 'telephone' => '+241 11 76 55 46', 'adresse' => ''],
            ['nom' => 'ETS N\'GNIGONE', 'email' => 'ngnigone@logistiga.com', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'PRESIDENCE DE LA REPUBLIQUE GABONAISE', 'email' => 'Gabonaise@logistiga.com', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'FONDATION OMAR BONGO ONDIMBA', 'email' => 'fondationobo@yahoo.fr', 'telephone' => '+241 66 07 61 95', 'adresse' => ''],
            ['nom' => 'WAIGALO IBRAHIM', 'email' => 'Ibrahim@logistiga.com', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'TRANSFORM', 'email' => 'contact@transform-ga.com', 'telephone' => '+241 66 22 61 06', 'adresse' => ''],
            ['nom' => 'PISTON GABON', 'email' => 'omar@piston-gabon.com', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'AIR LIQUIDE', 'email' => 'ALGabon@airliquide.com', 'telephone' => '011 70 27 15', 'adresse' => ''],
            ['nom' => 'CEDICOM', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'CHIMIE GABON', 'email' => 'IMPORT@CHIMIEGABON.COM', 'telephone' => '241472656', 'adresse' => ''],
            ['nom' => 'DAVUM GABON', 'email' => 'transit-2000@hotmail.fr', 'telephone' => '+241 01 17 43 214', 'adresse' => ''],
            ['nom' => 'GABONAISE DE CHIMIE', 'email' => 'logistique.gciae@gmail.com', 'telephone' => '+241 011 76 48 99', 'adresse' => ''],
            ['nom' => 'INTER MAT', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'LF PRINTING', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'LSG', 'email' => 'operation.transit@lsg-gabon.com', 'telephone' => '+241 011 70 71 65', 'adresse' => ''],
            ['nom' => 'MAERSK', 'email' => '', 'telephone' => '+241 011 70 31 36', 'adresse' => ''],
            ['nom' => 'SATOGA', 'email' => 'SATOGA2016@OUTLOOK.FR', 'telephone' => '+241 066 34 72 01', 'adresse' => ''],
            ['nom' => 'SIGALLI', 'email' => 'transit-2000@hotmail.fr', 'telephone' => '+241 066 44 11 90', 'adresse' => ''],
            ['nom' => 'SOMIVAB GABON', 'email' => 'm.sow@somivab.com', 'telephone' => '+241 011 44 28 70', 'adresse' => ''],
            ['nom' => 'SOTRALGA', 'email' => '', 'telephone' => '+241 011 70 32 69', 'adresse' => ''],
            ['nom' => 'TRACTAFRIC EQUIPEMENT GABON', 'email' => 'JUDES.MOUTENDY@TRACTAFRIC.COM', 'telephone' => '+241 77 29 53 30', 'adresse' => ''],
            ['nom' => 'CGPR', 'email' => 'transit-2000@hotmail.fr', 'telephone' => '+241 077 99 97 19', 'adresse' => ''],
            ['nom' => 'LES MATERIAUX REUNIS', 'email' => 'lmrgabon@yahoo.com', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'SICG', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'MESSAN AZIABA ASSIONVI', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'FOREVER LIVING PRODUCTS GABON SUARL', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'CEGAP', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'SOCIETE CRYSTAL', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'SOCIETE ADAM', 'email' => '', 'telephone' => '07121112', 'adresse' => ''],
            ['nom' => 'PIECES POIDS LOURDS', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'AMERICAN AMBASSADOR', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'CENTRE NATIONAL D\'HEMODIALYSE', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'RISOWOOD GABON', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'OLEH-VICTOR OKOKO', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'JOSEPH UDO', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'A.R.T', 'email' => 'k.moutsinga@artgabon.com', 'telephone' => '+241 11 73 79 40', 'adresse' => ''],
            ['nom' => 'UNCLE SAM', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'CHAUDRONNERIE DU GABON', 'email' => '', 'telephone' => '011 76 20 71', 'adresse' => ''],
            ['nom' => 'TOYOTA GABON', 'email' => 'toyota.gabon@groupesogafric.com', 'telephone' => '+241 77 15 16 13', 'adresse' => ''],
            ['nom' => 'GABON ADVENTURES', 'email' => 'GABONADEVENTURE@GAMIL.COM', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'GENERAL PRESTATION TRANSIT', 'email' => 'GPT@LOGISTIGA.COM', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'ETS OYOUWE', 'email' => 'Etsoyouwe@gmail.com', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'DHL GLOBAL', 'email' => 'guy.j.m.ossouma@dhl.com', 'telephone' => '011 44 43 32', 'adresse' => ''],
            ['nom' => 'SGTV', 'email' => 'transit-2000@hotmail.fr', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'TELEMENIA GABON', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'TRANSIT 2000', 'email' => '', 'telephone' => '011 74 74 69', 'adresse' => ''],
            ['nom' => 'SOGATRA', 'email' => '', 'telephone' => '+241 01 76 85 46', 'adresse' => ''],
            ['nom' => 'SIAT GABON', 'email' => 'gabon@siat-group.com', 'telephone' => '011722216', 'adresse' => ''],
            ['nom' => 'MARTIN PECHEUR', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'STEED REY', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'BATI PLUS', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'BATIGAM', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'GSEZ MINERAL PORT SA', 'email' => 'jeanine.menzene@arisenet.com', 'telephone' => '', 'adresse' => 'owendo'],
            ['nom' => 'ROYAL FOOD', 'email' => '', 'telephone' => '+241 65 98 13 98', 'adresse' => 'oloumi'],
            ['nom' => 'ETS HARRAZ', 'email' => 'Harraz@logistiga.com', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'NO JONAH', 'email' => 'Jonah@logistiga.com', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'TAM KOUAMBA', 'email' => 'Tam@logistiga.com', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => '5 STARS INTERNATIONAL', 'email' => 'Star@logistiga.com', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'S.L.C.M', 'email' => 'S@logistiga.com', 'telephone' => '', 'adresse' => 'owendo'],
            ['nom' => 'SOUNMANOU ALLADE NADJIMOU', 'email' => 'Allade@logistiga.com', 'telephone' => '', 'adresse' => 'owendo'],
            ['nom' => 'ALLOGHO MEYO JEAN FIDELE', 'email' => 'Jean@logistiga.com', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'MOUSSE INDUSTRIE', 'email' => 'sina@mousseindustrie.com', 'telephone' => '+241 11 77 31 91', 'adresse' => 'lbv'],
            ['nom' => 'LIBREMAT', 'email' => 'Libremat@logistiga.com', 'telephone' => '', 'adresse' => 'oloumi'],
            ['nom' => 'CIMAF GABON', 'email' => 'Cimaf@logistiga.com', 'telephone' => '', 'adresse' => 'owendo'],
            ['nom' => 'MEGA SERVICE', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'WEST LAKE IMPORT', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'ELECTRA', 'email' => '', 'telephone' => '', 'adresse' => 'oloumi'],
            ['nom' => 'NDIAYE DAOUDA', 'email' => '', 'telephone' => '', 'adresse' => 'libreville'],
            ['nom' => 'DIENG ABOUBACAR', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'BENKADI', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'AFRICA FROID INDUSTRIE', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'ALPHA MONDIAL', 'email' => '', 'telephone' => '', 'adresse' => 'oloumi'],
            ['nom' => 'HAIAT TRADING', 'email' => '', 'telephone' => '', 'adresse' => 'oloumi'],
            ['nom' => 'PIECES EQUIP AUTO', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'SEAL GABON S/C LECTRA', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'TOTAL MARKETING', 'email' => 'justine.ndong-obone@total.com', 'telephone' => '+241 11 79 40 69', 'adresse' => 'owendo'],
            ['nom' => 'SODIGAB', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'ETS SOLIDAIRE', 'email' => '', 'telephone' => '', 'adresse' => 'oloumi'],
            ['nom' => 'FOFANA MOHAMADOU', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'BUSINESS KING', 'email' => '', 'telephone' => '', 'adresse' => 'oloumi'],
            ['nom' => 'AMBASSADE DE RUSSIE', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'CE APRO GABON', 'email' => '', 'telephone' => '', 'adresse' => 'oloumi'],
            ['nom' => 'CERAMAT', 'email' => '', 'telephone' => '', 'adresse' => 'owendo'],
            ['nom' => 'IDEAL DISTRIBUTION', 'email' => '', 'telephone' => '', 'adresse' => 'oloumi'],
            ['nom' => 'SUNRISE DISTRIBUTION', 'email' => '', 'telephone' => '', 'adresse' => 'awendje'],
            ['nom' => 'MOUSTAPHA FATAI', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'AFRIK ET DISTRIBUTION', 'email' => '', 'telephone' => '02018536', 'adresse' => 'lbv'],
            ['nom' => 'ETS SUPER SERVICE', 'email' => '', 'telephone' => '', 'adresse' => 'oloumi'],
            ['nom' => 'SOCIETE ROMA', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'EPICERIE EL KHATAR', 'email' => '', 'telephone' => '', 'adresse' => 'oloumi'],
            ['nom' => 'AFRICA DEAL SARL', 'email' => '', 'telephone' => '', 'adresse' => 'oloumi'],
            ['nom' => 'ETS BONUS', 'email' => '', 'telephone' => '', 'adresse' => 'oloumi'],
            ['nom' => 'ASIAN AUTO GABON', 'email' => '', 'telephone' => '', 'adresse' => 'owendo'],
            ['nom' => 'MITRI CHRISTIAN', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'ELECTRO BAH', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'AUTO MAKKY', 'email' => '', 'telephone' => '', 'adresse' => 'oloumi'],
            ['nom' => 'SPOT SARL', 'email' => '', 'telephone' => '', 'adresse' => 'oloumi'],
            ['nom' => 'SA MARSHALL', 'email' => '', 'telephone' => '', 'adresse' => 'oloumi'],
            ['nom' => 'GIPP GABON', 'email' => '', 'telephone' => '', 'adresse' => 'owendo'],
            ['nom' => 'SAMBA', 'email' => '', 'telephone' => '', 'adresse' => 'oloumi'],
            ['nom' => 'ATTN:GAO TIAN XING', 'email' => '', 'telephone' => '', 'adresse' => 'owendo'],
            ['nom' => 'EPICERIE KATHIA', 'email' => '', 'telephone' => '', 'adresse' => 'owendo'],
            ['nom' => 'SOGAFRIC SERVICE', 'email' => '', 'telephone' => '', 'adresse' => 'oloumi'],
            ['nom' => 'PRECIOUS WOOD', 'email' => '', 'telephone' => '', 'adresse' => 'owendo'],
            ['nom' => 'GABON PNEUS', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'VIKRAM', 'email' => '', 'telephone' => '', 'adresse' => 'owendo'],
            ['nom' => 'EPICERIE FOFANA', 'email' => '', 'telephone' => '', 'adresse' => 'OLOUMI'],
            ['nom' => 'FOFANA SAYON', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'PT.HERAMAKONO', 'email' => '', 'telephone' => '', 'adresse' => 'oloumi'],
            ['nom' => 'ETS EZAMZAM', 'email' => '', 'telephone' => '', 'adresse' => 'oloumi'],
            ['nom' => 'OGTT', 'email' => '', 'telephone' => '', 'adresse' => 'oloumi'],
            ['nom' => 'DISTRIGA', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'SKINEVA', 'email' => 'ctigabon1@gmail.com', 'telephone' => '', 'adresse' => 'oloumi'],
            ['nom' => 'DRAME DEMBA ALASSANE', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'SHOP DIALLO', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'SOCIETE SEEF', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'WALATH IMPORT ET DISTRIBUTION', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'SODIM TP', 'email' => '', 'telephone' => '', 'adresse' => 'oloumi'],
            ['nom' => 'FONDATION SYLIVIA BONGO ONDIMBA', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'AMERICAN DREAM HOME', 'email' => '', 'telephone' => '', 'adresse' => 'angondje'],
            ['nom' => 'HARMONIE', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'GAO YUN', 'email' => '', 'telephone' => '074698656', 'adresse' => 'owendo'],
            ['nom' => 'EKOH ELLA CALVIN', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'DIALLO SAMBA', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'VESPERO GLOBAL FOOD', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'PRIX IMPORT', 'email' => '', 'telephone' => '', 'adresse' => 'oloumi'],
            ['nom' => 'MUTETI CENTER', 'email' => '', 'telephone' => '', 'adresse' => 'owendo'],
            ['nom' => 'CLIENT COMPTOIR', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'MR OBINNA PAUL CHINEDU', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'BALEMAYA', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'ABOU DIA', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'ACCURATE INDUSTRIES', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'SOFERGA', 'email' => '', 'telephone' => '', 'adresse' => 'owendo'],
            ['nom' => 'BOUMA BOURAIMA', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'PHILLIPPE KAFILATOU', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'BABA NIMAGA', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'FAMOGA', 'email' => '', 'telephone' => '', 'adresse' => 'owendo'],
            ['nom' => 'BAH OMAR', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'ILAM ILEC', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'SYLLA ET FRERE', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'NWACHUKWU PRINCEWILL', 'email' => 'princechukwu85@yahoo.com', 'telephone' => '062085650', 'adresse' => ''],
            ['nom' => 'AMMAR MOHAMED', 'email' => '', 'telephone' => '', 'adresse' => 'owendo'],
            ['nom' => 'LY ABDOULAYE', 'email' => '', 'telephone' => '', 'adresse' => 'LBV'],
            ['nom' => 'ETS YAYA', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'ROYAL PLAZA', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'STAR INDUSTRIE', 'email' => '', 'telephone' => '', 'adresse' => 'owendo'],
            ['nom' => 'SOUBEROU RAFIOU', 'email' => '', 'telephone' => '', 'adresse' => 'owendo'],
            ['nom' => 'MME NDOUO PEGGY ET MR OGNAGNA HANS STEPHANE', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'GEORGE UCHE', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'H.M.DISTRIBUTION', 'email' => '', 'telephone' => '', 'adresse' => 'oloumi'],
            ['nom' => 'S.E.E.T', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'SIDILIG', 'email' => '', 'telephone' => '', 'adresse' => 'oloumi'],
            ['nom' => 'NDIAYE HAMET', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'SAMBA DIA', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'OBS COSMETIQUE', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'TECHNICALU', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'DIAWARA ADAMA', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'MAMMAMI CHERRI ATEF', 'email' => '', 'telephone' => '', 'adresse' => 'owendo'],
            ['nom' => 'CGE GABON', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'AVOMO VICTORINE ISABELLE', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'FOBERT GABON', 'email' => '', 'telephone' => '', 'adresse' => 'owendo'],
            ['nom' => 'OBINNA PAUL CHINEDU', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'BA MOHAMED', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'GOLF DISTRIBUTION', 'email' => '', 'telephone' => '', 'adresse' => 'oloumi'],
            ['nom' => 'GABON WOOD', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'MME KOUMBA DEMBOUMBA ADRIA TATIANA', 'email' => 'koumba@yahoo.fr', 'telephone' => '02332923', 'adresse' => 'lbv'],
            ['nom' => 'BULDOZER', 'email' => '', 'telephone' => '01763215', 'adresse' => 'oloumi'],
            ['nom' => 'BANDJOUGOU DIAWARA', 'email' => 'bandjou@gmail.com', 'telephone' => '077582696', 'adresse' => 'lbv'],
            ['nom' => 'OLIVE CARGO', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'ENAZAHA DISTRIBUTION', 'email' => 'CTIGABON1@GMAIL.COM', 'telephone' => '+241 77 85 85 05', 'adresse' => ''],
            ['nom' => 'SOTRASGAB', 'email' => 'infos@sotrasgab.com', 'telephone' => '+241 65 65 80 31', 'adresse' => ''],
            ['nom' => 'MAHDI PIECES DETACHEES', 'email' => '', 'telephone' => '', 'adresse' => 'owendo'],
            ['nom' => 'NONNI DRAMANE', 'email' => 'Dramane@gmail.com', 'telephone' => '066329027', 'adresse' => 'LBV'],
            ['nom' => 'IKECHUKWU OBIMBA', 'email' => '', 'telephone' => '', 'adresse' => 'owendo'],
            ['nom' => 'ARCHEMIA', 'email' => '', 'telephone' => '', 'adresse' => 'lbv'],
            ['nom' => 'CTI', 'email' => 'CTIGABON1@GMAIL.COM', 'telephone' => '077858505', 'adresse' => 'owendo'],
            ['nom' => 'DIABY MAHAMADOU', 'email' => '', 'telephone' => '07772890', 'adresse' => 'lbv'],
            ['nom' => 'ALI MOUSSA', 'email' => '', 'telephone' => '07123113', 'adresse' => 'lbv'],
            ['nom' => 'CAMARA ABDOULAYE', 'email' => '', 'telephone' => '0777165812', 'adresse' => 'lbv'],
            ['nom' => 'PHARAOH ALIMINIUM', 'email' => '', 'telephone' => '07845320', 'adresse' => 'lbv'],
            ['nom' => 'VITALIS', 'email' => '', 'telephone' => '07282493', 'adresse' => ''],
            ['nom' => 'CHUKWUNYERE DAVID', 'email' => '', 'telephone' => '02039487', 'adresse' => ''],
            ['nom' => 'EBAI NDIP MIRABEL EYONG', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'TALA SHOP', 'email' => '', 'telephone' => '062113504', 'adresse' => ''],
            ['nom' => 'SUARL GOLF DILT', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'ETS LORINA', 'email' => '', 'telephone' => '074875626', 'adresse' => ''],
            ['nom' => 'BAH ALIOU', 'email' => '', 'telephone' => '07987911', 'adresse' => ''],
            ['nom' => 'BELLO KAOSSARA', 'email' => 'AMAKEBELLO11@GMAI.COM', 'telephone' => '06193806', 'adresse' => ''],
            ['nom' => 'ETS DIAWARA MOUTIQUE', 'email' => '', 'telephone' => '07609825', 'adresse' => ''],
            ['nom' => 'CHIMIOTECHNIC SARL', 'email' => '', 'telephone' => '066297205', 'adresse' => ''],
            ['nom' => 'FRIDAG', 'email' => '', 'telephone' => '+241 62 11 11 18', 'adresse' => ''],
            ['nom' => 'ETS KABA', 'email' => 'dialkab@gmail.com', 'telephone' => '+241 62 94 12 53', 'adresse' => ''],
            ['nom' => 'PETSHOP GABON', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'SIM BTP SARL', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'ULTIMATE MARINE GABON', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'PETIT DUBAI SHOP', 'email' => '', 'telephone' => '+241 65 65 78 30', 'adresse' => ''],
            ['nom' => 'MME TCHEGNON AMELE GREMAINE', 'email' => '', 'telephone' => '+241 077 15 42 30', 'adresse' => ''],
            ['nom' => 'NGOBIWU EPSE EDOM CHIGOZIE', 'email' => 'francisosuemele@yahoo.com', 'telephone' => '+241 77 31 78 53', 'adresse' => ''],
            ['nom' => 'TMT', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'DUBAI AVENUE', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'TRIANON BTP GABON', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'SUPER GEL', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'ECOWOOD SA', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'NGOUAYIEMO FEUNE JEAN PAUL', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'ETS FARRO ET FRERES', 'email' => '', 'telephone' => '+241 74 19 53 37', 'adresse' => ''],
            ['nom' => 'TAN YUYAN', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'PEMBA EP KASSA JEANNETTE', 'email' => '', 'telephone' => '+241 77 25 41 23', 'adresse' => ''],
            ['nom' => 'ZENGUE MASSALA', 'email' => '', 'telephone' => '+241 62 70 09 09', 'adresse' => ''],
            ['nom' => 'ASTOU NDOYE', 'email' => 'ASTOUNDOYE.DISTGB@GMAIL.COM', 'telephone' => '+241 77 14 54 24', 'adresse' => ''],
            ['nom' => 'LES BATISSEURS REUNIS', 'email' => '', 'telephone' => '+241 65 03 81 24', 'adresse' => ''],
            ['nom' => 'KAROUNGA DEAMBO POINTE PASTALE', 'email' => 'abdoulayediawara60@gmail.com', 'telephone' => '+241 77 75 75 80', 'adresse' => ''],
            ['nom' => 'MATERIAUX VALENCIA', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'AFRIQUE EUROPE ASIE', 'email' => '', 'telephone' => '+241 77 17 01 59', 'adresse' => ''],
            ['nom' => 'SNEF GABON', 'email' => 'libreville@snefgabon.com', 'telephone' => '+241 11 74 07 55', 'adresse' => ''],
            ['nom' => 'WOTEDMAS TRANSIT SARL P/C ECOLE MAARIF TURCO GABONAISE', 'email' => '', 'telephone' => '+241 62 55 22 2', 'adresse' => ''],
            ['nom' => 'SETRAG', 'email' => 'communication@setrag.com', 'telephone' => '+241 66 99 82 44', 'adresse' => ''],
            ['nom' => 'FROIDELLE GABON SUARL', 'email' => '', 'telephone' => '+241 62 19 18 17', 'adresse' => ''],
            ['nom' => 'DOMTA TRADING COMPANY GABON', 'email' => 'DTCG.TRANSPORT@GMAIL.COM', 'telephone' => '+241 77 86 35 34', 'adresse' => ''],
            ['nom' => 'DIALLO AMADOU', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'SIVVA', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'SOCIETE CITP', 'email' => '', 'telephone' => '+241 66 22 375', 'adresse' => ''],
            ['nom' => 'OFFICE PHARMACEUTIQUE NATIONAL', 'email' => 'opn_gabon@yahoo.fr', 'telephone' => '+241 11 76 55 07', 'adresse' => ''],
            ['nom' => 'GUY ROGER NDOBANI', 'email' => '', 'telephone' => '+241 66 85 72 08', 'adresse' => ''],
            ['nom' => 'ETISALAT GABON', 'email' => 'MODIBOYARA@HOTMAIL.FR', 'telephone' => '+241 77 99 73 73', 'adresse' => ''],
            ['nom' => 'KANE BASSIROU', 'email' => '', 'telephone' => '+241 77 77 86 77', 'adresse' => ''],
            ['nom' => 'IBRAHIM TANDIA', 'email' => '', 'telephone' => '+241 62 47 62 0', 'adresse' => ''],
            ['nom' => 'IBRAHIM SOW', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'KONATE', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'AFRITAG', 'email' => '', 'telephone' => '+241 62 11 11 18', 'adresse' => ''],
            ['nom' => 'IDEES 2000', 'email' => 'obricard@idees-2000.com', 'telephone' => '+241 66 24 84 80', 'adresse' => ''],
            ['nom' => 'KA ABASS', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'DIA DAHIROU', 'email' => 'sales5@epsp.fr', 'telephone' => '+241 66 47 39 20', 'adresse' => ''],
            ['nom' => 'NDIAYE DJIBRIL', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'ADA BIDANG', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'SOCIETE DE VENTE DES PIECES D AUTO', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'DRILLMEX GABON', 'email' => 'francisosuemele@yahoo.fr', 'telephone' => '+241 77 31 78 53', 'adresse' => ''],
            ['nom' => 'LIYAMA NTCHLEGUI JESSICA PATTEN PRICILLIA', 'email' => 'LIYALESS@HOTMAIL.FR', 'telephone' => '+241 66 20 83 17', 'adresse' => ''],
            ['nom' => 'MR NDIAYE', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'EYEGHE MBOUROU Marth E.', 'email' => '', 'telephone' => '+241 77 67 618', 'adresse' => ''],
            ['nom' => 'LA MAISON MODERNE', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'SOCIETE MAKSDOUD', 'email' => '', 'telephone' => '+241 65 73 41 41', 'adresse' => ''],
            ['nom' => 'OKONKWO EDWIN', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'AHMET SALEH', 'email' => 'HAMIDVISSA@YAHOO.FR', 'telephone' => '+241 77 77 53 53', 'adresse' => ''],
            ['nom' => 'MR UKANWA LUCKY KELECHI', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'BOUBOU SYLLA', 'email' => 'SYLLA@GMAIL.COM', 'telephone' => '+241 74 42 82 89', 'adresse' => ''],
            ['nom' => 'MBAYE SALIOU', 'email' => 'MBAYESALIOU44@YAHOO.FR', 'telephone' => '+241 66 23 32 97', 'adresse' => ''],
            ['nom' => 'SOCIETE BE-TECH', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'OUMAR BAH', 'email' => 'yara.smart@gmail.com', 'telephone' => '+241 74 65 25 25', 'adresse' => ''],
            ['nom' => 'FOFANA ABDULAYE', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'ECIG', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'FZ DISTRIBUTION', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'RATEL', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'ISTANBUL GABON', 'email' => '', 'telephone' => '+241 06 24 91 99', 'adresse' => ''],
            ['nom' => 'AMOUSSA MOUISSOU', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'DISPRAL GABON', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'LA PRINCESS LEA', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'BISSIRIOU GANIOU', 'email' => '', 'telephone' => '+241 04 91 74 22', 'adresse' => ''],
            ['nom' => 'EMITAG', 'email' => '', 'telephone' => '+241 65 88 08 08', 'adresse' => ''],
            ['nom' => 'MR KANE', 'email' => '', 'telephone' => '+241 77 77 86 77', 'adresse' => ''],
            ['nom' => 'MEDEX', 'email' => 'medex.ga@gmail.com', 'telephone' => '+241 077 61 64 00', 'adresse' => ''],
            ['nom' => 'SERAL ALUMINUM', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'BGFI BANK GABON', 'email' => 'r.terout@bgfi.com', 'telephone' => '+241 01 44 17 10', 'adresse' => ''],
            ['nom' => 'CENECOM', 'email' => 'comcenecom@gmail.com', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'TFE GABON', 'email' => 'phillippe.mokoko@grouptfe.com', 'telephone' => '+241 62 12 37 37', 'adresse' => ''],
            ['nom' => 'ZITA FLORA', 'email' => 'gisoulemina@msn.com', 'telephone' => '+241 66 21 20 68', 'adresse' => ''],
            ['nom' => 'ETS SUPER STAR', 'email' => '', 'telephone' => '+241 77 72 22 72', 'adresse' => ''],
            ['nom' => 'NOMAD', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'AFRICAN BUSUNESS CORPORATION', 'email' => '', 'telephone' => '+241 62 80 36 90', 'adresse' => ''],
            ['nom' => 'PROLIFT SARL', 'email' => '', 'telephone' => '+241 77 52 52 22', 'adresse' => ''],
            ['nom' => 'IBCOM', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'CODALEC', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'ONWUBGULE EDUKA BRUNO', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'I.E.V RODRIGUE', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'SARIC', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'MINLA OBIANG FELIX', 'email' => '', 'telephone' => '+241 66 26 51 46', 'adresse' => ''],
            ['nom' => 'PS GABON', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'TMAC', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'S-OIL', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'ETS RANDY', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'GABON AUTO PLUS', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'PAUL ET FRERE', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'SEHO KOISSI EVARISTE', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'GETRACO', 'email' => '', 'telephone' => '066227579', 'adresse' => ''],
            ['nom' => 'GABON MINING', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'AB COM/ BOCOUM', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'GAOTIANXING', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'WASSOMBOUTSENGHE NINA', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'FRANCIS', 'email' => 'francisosuemele@yahoo.fr', 'telephone' => '+241 77 31 78 53', 'adresse' => ''],
            ['nom' => 'PYRAMID ENGINEERING', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'ETOILE D\'OR', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'MULTIPRESS', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'FPA GABON FABRICATION PRODUIT', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'MEQUAFRIP', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'MBELE ASSEKO JULES', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'HOUDA WEHBE', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'LES AMIS BOUTIQUE', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'RESTAU GROUP', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'BONJOUR COMPAGNIE GABON', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'ETS GNINGUE', 'email' => '', 'telephone' => '077317853', 'adresse' => ''],
            ['nom' => 'AVARO GILBERT GUY ROGER', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'L\'HABITAT', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'CONSTRUCTION BDS SUARL', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'NOUVELLE GABON MINING', 'email' => 'contact@nouvellegabonmining.com', 'telephone' => '+241 11 73 05 30', 'adresse' => ''],
            ['nom' => 'SOCIETE AUDREY CONSTRUCTION', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'DEMBELE YOUSSOUF', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'GABON SPRINT AUTO', 'email' => 'contact@gr-gsa.com', 'telephone' => '+241 11 72 25 14', 'adresse' => ''],
            ['nom' => 'DOUKEMAT', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'CENTRALE PNEU + GABON', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'LAMINE SYLA', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'SAID', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'NGOYE GOUNDO CAMARA', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'LIFEMATE MEUBLES', 'email' => '', 'telephone' => '+241 62 05 99 99', 'adresse' => ''],
            ['nom' => 'DIAWARA DABA', 'email' => '', 'telephone' => '066589397', 'adresse' => ''],
            ['nom' => 'SYLLA ASSETOU', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'MARKET IMPORT', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'ALUTEX GABON', 'email' => '', 'telephone' => '066810242', 'adresse' => ''],
            ['nom' => 'STE GOMA ZONA', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'ETAT MAJOR', 'email' => '', 'telephone' => '065441059', 'adresse' => ''],
            ['nom' => 'ALIMENTATION LEADERS INTERNATIONALE', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'TAPIRAMA', 'email' => '', 'telephone' => '066412221', 'adresse' => ''],
            ['nom' => 'DEPOT D\'ENTREPRISE DAVICULTURE GABON', 'email' => '', 'telephone' => '065540249', 'adresse' => ''],
            ['nom' => 'LUXURY CARS', 'email' => 'luxury.car20@gmail.com', 'telephone' => '+241 60 00 33 33', 'adresse' => ''],
            ['nom' => 'BOULANGERIE PATISSERIE PELISSON', 'email' => '', 'telephone' => '+241 11 76 52 58', 'adresse' => ''],
            ['nom' => 'AMOUZOU KOSSI MITRONUNYA', 'email' => '', 'telephone' => '062747300', 'adresse' => ''],
            ['nom' => 'SACKO DRAMANE', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'SOUMARE ABDOUL AZIZ', 'email' => '', 'telephone' => '065425858', 'adresse' => ''],
            ['nom' => 'HOME VIDEO COMPANY', 'email' => 'contact@homevideo.ga', 'telephone' => '+241 77 06 06 00', 'adresse' => ''],
            ['nom' => 'LEONCE ROMUALD TOUNGUI', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'TOP FRUITS', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'MEDLOG', 'email' => 'GAB-info@medlog.com', 'telephone' => '074406444', 'adresse' => ''],
            ['nom' => 'NWOKO MATTHEW', 'email' => '', 'telephone' => '077940189', 'adresse' => ''],
            ['nom' => 'LI JIANHUA', 'email' => '', 'telephone' => '+241 74 36 25 37', 'adresse' => ''],
            ['nom' => 'SOCIETE SUPER PREMIER', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'NWAGWU CHIKA CHRISTOPHER', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'DABABOUGOU', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'FLY HOTEL', 'email' => 'info@flyhotelgabon.com', 'telephone' => '+241 11 44 21 71', 'adresse' => ''],
            ['nom' => 'SYLLA MAMADOU', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'EME JUDE UCHE', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'GABON TOLES', 'email' => '', 'telephone' => '+241 62 47 33 10', 'adresse' => ''],
            ['nom' => 'FONDATION LES ENFANTS DU PADOUK', 'email' => 'enfantsdupadouk@gmail.com', 'telephone' => '+241 62 04 12 36', 'adresse' => ''],
            ['nom' => 'ANGANGOULENDOYE VIVIANE', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'SALAKO ABIOLA MATHIEU', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'ETS KONAWIRI ET FRERES', 'email' => '', 'telephone' => '+241 62 86 84 46', 'adresse' => ''],
            ['nom' => 'GABON SERVICE AUTO', 'email' => '', 'telephone' => '+241 77 14 10 78', 'adresse' => ''],
            ['nom' => 'NAUTICA EQUIPMENT SARL', 'email' => 'nautica.eqipment@gmail.com', 'telephone' => '+241 65 75 00 00', 'adresse' => ''],
            ['nom' => 'POMMY', 'email' => '', 'telephone' => '+241 062 22 09 22', 'adresse' => ''],
            ['nom' => 'EXCELLENCE OK DISTRIBUTION', 'email' => '', 'telephone' => '+241 66 24 31 24', 'adresse' => ''],
            ['nom' => 'SABAY SALIF', 'email' => '', 'telephone' => '+241 07 40 68 90', 'adresse' => ''],
            ['nom' => 'ETS PRINCEWILL', 'email' => '', 'telephone' => '+241 62 08 56 50', 'adresse' => ''],
            ['nom' => 'FRIP TATA', 'email' => '', 'telephone' => '+241 07 31 36 65', 'adresse' => ''],
            ['nom' => 'INTERLABO SERVICE SARL', 'email' => '', 'telephone' => '241443958', 'adresse' => ''],
            ['nom' => 'IMPEX TRADING', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'CLEAN AFRICA', 'email' => '', 'telephone' => '+241 65 03 43 15', 'adresse' => ''],
            ['nom' => 'CONIUM', 'email' => '', 'telephone' => '+241 66 77 77 65', 'adresse' => ''],
            ['nom' => 'ETS CHIDI', 'email' => 'anyanwuudo2@gmail.com', 'telephone' => '+241 66 45 02 45', 'adresse' => ''],
            ['nom' => 'MUTWA MAYAMBA', 'email' => 'mutw@yahoo.com', 'telephone' => '+241 62 37 900', 'adresse' => ''],
            ['nom' => 'CODIREL', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'INTER LUX', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'EVERGREEN GABON ZERP', 'email' => 'evergreengabon@gmail.com', 'telephone' => '+241 66 57 80 07', 'adresse' => ''],
            ['nom' => 'STE BTSG', 'email' => '', 'telephone' => '+241 77 41 00 00', 'adresse' => ''],
            ['nom' => 'GABLCHE P/C SAINT PHILIPPE', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'LP CONSULTING', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'ELECTROGAB PLUS SUARL', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'TRIOMPHE TRANSPORT', 'email' => '', 'telephone' => '+241 77 03 65 79', 'adresse' => ''],
            ['nom' => 'SOCIETE DE TRANSFORMATION ET DE COMMERCE', 'email' => '', 'telephone' => '+241 65 01 81 61', 'adresse' => ''],
            ['nom' => 'LENDIE EP EMBIGA AMOGHO SYLVIE', 'email' => '', 'telephone' => '+241 66 26 96 44', 'adresse' => ''],
            ['nom' => 'ONTSOUGOU MBANI HERVE SYLVERE', 'email' => 'badirou.sadia@gmail.com', 'telephone' => '+241 62 03 71 14', 'adresse' => ''],
            ['nom' => 'ETS MCF', 'email' => 'lemamicherriatef@hotmail.com', 'telephone' => '+241 77 37 60 88', 'adresse' => ''],
            ['nom' => 'GABON PREFAB HANCAR', 'email' => 'jomaanashaat@yahoo.com', 'telephone' => '+241 62 43 08 43', 'adresse' => ''],
            ['nom' => 'NGUEMA BEKALE ROCH', 'email' => '', 'telephone' => '+241 66 49 49 15', 'adresse' => ''],
            ['nom' => 'SOMAF', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'CLAUDINE NTCHORERE', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'MIAG SA', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'WORL WIDE COMPAGNY', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'LYCEE FRANCO BRITANNIQUE', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'SGVS', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'ACEWOOD GABON', 'email' => 'karimchehab@hotmail.com', 'telephone' => '+241 66 99 99 99', 'adresse' => ''],
            ['nom' => 'NTSAME MBA MARIE LOUISE', 'email' => '', 'telephone' => '+241 66 46 94 41', 'adresse' => ''],
            ['nom' => 'GMAD', 'email' => 'contact@africamat.com', 'telephone' => '+241 74 23 03 01', 'adresse' => ''],
            ['nom' => 'MBINIE MOMBO MARVIN LIONEL', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'DERKRAS INSPECTION GABON', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'BERVILLE JEAN CLAUDE', 'email' => '', 'telephone' => '+241 74 65 83 42', 'adresse' => ''],
            ['nom' => 'P.L.M', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'PRESTIGE 5262', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'ENACO', 'email' => '', 'telephone' => '+241 46 66 70 562', 'adresse' => ''],
            ['nom' => 'T.E.S.G', 'email' => '', 'telephone' => '+241 66 40 14 05', 'adresse' => ''],
            ['nom' => 'SO.AFRI.COM', 'email' => '', 'telephone' => '+241 65 74 17 68', 'adresse' => ''],
            ['nom' => 'CGA', 'email' => 'ouerfelli.nizar@gmail.com', 'telephone' => '+241 11 77 33 61', 'adresse' => ''],
            ['nom' => 'OLOUMI CENTER', 'email' => '', 'telephone' => '+241 77 28 28 84', 'adresse' => ''],
            ['nom' => 'MR OBIANG', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'ALFIA COLOR VERNICI', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'OBONE ELLA MADELEINE', 'email' => '', 'telephone' => '+241 77 66 69 78', 'adresse' => ''],
            ['nom' => 'VIVO ENERGY GABON', 'email' => '', 'telephone' => '+241 77 98 60 41', 'adresse' => ''],
            ['nom' => 'AFRICA CEMENT AND STEEL', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'LIONEL PARFAIT MBA MOUDOUHI', 'email' => 'lionelmb1986@gmail.com', 'telephone' => '+241 74 83 29 92', 'adresse' => ''],
            ['nom' => 'DUBAI ACCESSOIRES', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'MR MBOUDI BOULINGUI DONJAIME', 'email' => 'mboudiboul@hotmail.com', 'telephone' => '+241 062 96 72 59', 'adresse' => ''],
            ['nom' => 'CMA CGM', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'LEONAURE NEW SERVICE', 'email' => 'kodsarl2014@gmail.com', 'telephone' => '+241 66 24 54 79', 'adresse' => ''],
            ['nom' => 'ONG OPERATION CADEAUX POUR TOUS', 'email' => '', 'telephone' => '+241 66 07 70 29', 'adresse' => ''],
            ['nom' => 'MIKA SERVICES', 'email' => '', 'telephone' => '065655524', 'adresse' => ''],
            ['nom' => 'NDONG ESSONO YVES KARL', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'OYONO OBIANG FIDELE', 'email' => 'bgfidle@yahoo.fr', 'telephone' => '+241 77 59 29 99', 'adresse' => ''],
            ['nom' => 'EURYDICE LOLITA OWANGA NGUEMA', 'email' => '', 'telephone' => '+241 77 17 64 63', 'adresse' => ''],
            ['nom' => 'WU XUE PING', 'email' => '', 'telephone' => '+241 077 78 99 99', 'adresse' => ''],
            ['nom' => 'DOGOCO', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'KOUOTOU AMADOU', 'email' => 'kouotou@yahoo.fr', 'telephone' => '+241 77 51 63 74', 'adresse' => ''],
            ['nom' => 'AGES', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'MR FOFANA', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'MR WILFREDE', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'STE DE TRAITEMENT D EAU MINERAL', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'SERVICE SANTE MILITAIRE', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'NZENGUE FACE D ANGE', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'ESTTM CO', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'TOURE SEKOU', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'SYLLA SEKOU', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'DGSSM-MANOEUVRE2022', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'SINDHYDRO', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'NI LI XU', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'MISSIENGHO MIGOLET BRICE MARTIN', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'DJOUNGA MAGNOUMBA KEVIN NOEL', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'SOPATGA', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'TAMBADOU', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'HASSINA BUSINESS', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'SOEF', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'REDA HELAL SELIM MOHAMED', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'L AGENCE NATIONAL DES BOURSES DU GABON', 'email' => 'Agence@logistiga.com', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'OMAR EL AMRAOUI', 'email' => 'omar@logistiga.com', 'telephone' => '011701435', 'adresse' => 'OWENDO SETRAG AVONS SIMAF'],
            ['nom' => 'GABON ALIMENTATION', 'email' => '', 'telephone' => '', 'adresse' => 'OWENDO'],
            ['nom' => 'PETRO GABON', 'email' => 'PITRO@PISTON.COM', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'MR SACKO', 'email' => '', 'telephone' => '', 'adresse' => 'OWENDO'],
            ['nom' => 'GPT', 'email' => '', 'telephone' => '', 'adresse' => 'OWENDO'],
            ['nom' => 'MR MUSTAPHA', 'email' => 'MUSTAPHA.A@LOGISTIGA.COM', 'telephone' => '', 'adresse' => 'OWENDO'],
            ['nom' => 'CILENT DIVERS', 'email' => '', 'telephone' => '', 'adresse' => 'OWENDO'],
            ['nom' => 'ART DECO', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'SOMIVAB', 'email' => '', 'telephone' => '', 'adresse' => ''],
            ['nom' => 'MINISTERE DE LA SANTE', 'email' => '', 'telephone' => '', 'adresse' => 'LIBREVILLE'],
            ['nom' => 'ETS SAFIE', 'email' => '', 'telephone' => '', 'adresse' => 'LIBREVILLE'],
            ['nom' => 'EVANS NDILI MFOUMBAT', 'email' => '', 'telephone' => '066005066', 'adresse' => 'OWENDO'],
            ['nom' => 'EXODUS TRANSPORT', 'email' => 'EXODUS@GMAIL.COM', 'telephone' => '', 'adresse' => 'OWENDO'],
            ['nom' => 'ICHAM', 'email' => 'ICHAM@GMAIL.COM', 'telephone' => '', 'adresse' => 'OWENDO'],
        ];

        foreach ($clients as $data) {
            Client::create([
                'nom' => $data['nom'],
                'email' => $data['email'] ?: null,
                'telephone' => $data['telephone'] ?: null,
                'adresse' => $data['adresse'] ?: null,
                'ville' => 'Libreville',
                'solde' => 0,
            ]);
        }

        // Transitaires importés depuis la base legacy (~125 transitaires)
        $transitaires = [
            ['nom' => 'SEPT', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'PIN SHANG - COULIBALY', 'telephone' => '+241 07870524', 'email' => '', 'adresse' => ''],
            ['nom' => 'AUTC', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'TRANSIT 2000', 'telephone' => '', 'email' => 'transit2000@logistiga.com', 'adresse' => ''],
            ['nom' => 'AUTC - MAMADI', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'NV TRANSIT - MOHAMED', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'BOCOUM', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'SDV', 'telephone' => '', 'email' => 'SDV@LOGISTIGA.COM', 'adresse' => ''],
            ['nom' => 'COULIBALY', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'SYLLA', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'ICHAM', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'DHL', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'MALICK', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'CHAOUKI', 'telephone' => '+241 65303809', 'email' => 'chaoukimas30@gmail.com', 'adresse' => ''],
            ['nom' => 'TMT', 'telephone' => '+241 11707363', 'email' => 'contact@tmtransit.com', 'adresse' => ''],
            ['nom' => 'T.M.A.C', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'AITC', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'JUNIOR', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'AMIDOU', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'CATRAMAC', 'telephone' => '+241 06130554', 'email' => '', 'adresse' => ''],
            ['nom' => 'SGT', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'BM TRANSITE', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'ETL', 'telephone' => '+241 06614100', 'email' => 'commercial.etl241@gmail.com', 'adresse' => ''],
            ['nom' => 'MR MARTIN', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'OGTT', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'BOLLORE', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'GETRACO', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'TRIANON BTP', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'DELTA TRANSIT', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'GEORGE', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'SGTA', 'telephone' => '+241 07501242', 'email' => '', 'adresse' => ''],
            ['nom' => 'UCO', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'STSG', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'NDIAYE', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'KABA BANGALY', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'STARPLY GABON', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'LUIGY', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'TRALOG', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'FRET TAM', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'STT', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'ASG', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'SGTM', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'FABUS', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'SAMY', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'JULE NZE', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'STS', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'CAP TRANSIT', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'SERVICE TRANSIT', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'FOFANA', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'TATA SHIPING', 'telephone' => '+241 77384071', 'email' => 'nomokongoma@yahoo.fr', 'adresse' => ''],
            ['nom' => 'SOMATRANS', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'MAERSK', 'telephone' => '', 'email' => 'ga.import@maersk.com', 'adresse' => ''],
            ['nom' => 'MEDLOG', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'GLOBAL TRANSIT', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'MILENIUM SERVICE PLUS', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'MBA', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'TRANSTAR', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'M.T.L.', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'WALID', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'ITRAMA', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'SOGAT', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'SALAM', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => '2RC-INTER', 'telephone' => '+241 07276465', 'email' => '', 'adresse' => ''],
            ['nom' => 'STGS', 'telephone' => '+241 06589144', 'email' => '', 'adresse' => ''],
            ['nom' => 'TCH', 'telephone' => '+241 07892660', 'email' => '', 'adresse' => ''],
            ['nom' => 'MTL GABON', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'MCTT', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'SO.GA.TT', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'BTPS', 'telephone' => '+241 77651570', 'email' => '', 'adresse' => ''],
            ['nom' => 'CEM - MOUSTAPHA', 'telephone' => '+241 05999781', 'email' => '', 'adresse' => ''],
            ['nom' => 'T.A.G', 'telephone' => '+241 77819690', 'email' => '', 'adresse' => ''],
            ['nom' => 'A.D.C', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'GSEZ', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'CETAN', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'LOUIGHY', 'telephone' => '+241 66087311', 'email' => '', 'adresse' => ''],
            ['nom' => 'UNIVERSEL TRANSIT', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'TNS', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'LSG', 'telephone' => '+241 11705726', 'email' => 'junior.yenda@lsg-gabon.com', 'adresse' => 'Owendo'],
            ['nom' => 'NOUVELLE VISION TRANSIT', 'telephone' => '', 'email' => '', 'adresse' => 'Owendo'],
            ['nom' => 'GPT', 'telephone' => '', 'email' => '', 'adresse' => 'Owendo'],
            ['nom' => 'ART', 'telephone' => '+241 65998151', 'email' => 'k.moutsiga@artgabon.com', 'adresse' => 'Owendo'],
            ['nom' => 'THIAM', 'telephone' => '', 'email' => '', 'adresse' => 'Owendo'],
            ['nom' => 'FRANCIS', 'telephone' => '+241 77317853', 'email' => '', 'adresse' => 'Owendo'],
            ['nom' => 'BUSINESS AIR LOGISTICS', 'telephone' => '+241 66198454', 'email' => '', 'adresse' => 'ACAE'],
            ['nom' => 'MULTI-SERVICE TRANSIT', 'telephone' => '', 'email' => '', 'adresse' => 'Oloumi'],
            ['nom' => 'MASAOUD', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'TMAC', 'telephone' => '', 'email' => '', 'adresse' => 'Libreville'],
            ['nom' => 'CTI', 'telephone' => '+241 62143402', 'email' => '', 'adresse' => 'Owendo'],
            ['nom' => 'FORMALIS', 'telephone' => '+241 77534576', 'email' => 'drameramamadou2018@gmail.com', 'adresse' => 'Libreville'],
            ['nom' => 'KANE', 'telephone' => '', 'email' => '', 'adresse' => 'Libreville'],
            ['nom' => 'BIC-TRANS', 'telephone' => '+241 62113504', 'email' => '', 'adresse' => ''],
            ['nom' => 'GTGA', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'KENNEDY', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'TRANSGAB', 'telephone' => '+241 77363618', 'email' => 'giggs504@yahoo.fr', 'adresse' => ''],
            ['nom' => 'INTER-TRANSIT GABON', 'telephone' => '+241 66004341', 'email' => 'intertransitgabon@gmail.com', 'adresse' => ''],
            ['nom' => 'RAPIDE TRANSIT FRET', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'CTAM', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'NAVI TRANS', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'B.A.T', 'telephone' => '+241 77244347', 'email' => '', 'adresse' => ''],
            ['nom' => 'APRETRAC', 'telephone' => '+241 66412221', 'email' => 'dissouchr@yahoo.fr', 'adresse' => ''],
            ['nom' => 'SACO', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'DOUKMAT', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'MTN', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'ISSIAKA', 'telephone' => '+241 66011022', 'email' => '', 'adresse' => ''],
            ['nom' => 'DJANE', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'ADC', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'GAPS', 'telephone' => '+241 11706289', 'email' => '', 'adresse' => ''],
            ['nom' => 'DIAKITE', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'MR SIDY', 'telephone' => '+241 62794918', 'email' => '', 'adresse' => ''],
            ['nom' => 'MOHAMED DIAKITE', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'BAKAYOKO', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'MR SALAM', 'telephone' => '+241 77870524', 'email' => '', 'adresse' => ''],
            ['nom' => 'SACKO DRAMANE', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'MR DIABY', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'MR PAUL HENRI', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'MR MOUSSA', 'telephone' => '', 'email' => '', 'adresse' => ''],
            ['nom' => 'MR MAHAMOUDOU', 'telephone' => '+241 60321168', 'email' => '', 'adresse' => ''],
            ['nom' => 'MR DICKO', 'telephone' => '+241 60321168', 'email' => '', 'adresse' => ''],
            ['nom' => 'G.E.T', 'telephone' => '', 'email' => '', 'adresse' => ''],
        ];

        foreach ($transitaires as $data) {
            Transitaire::create([
                'nom' => $data['nom'],
                'email' => $data['email'] ?: null,
                'telephone' => $data['telephone'] ?: null,
                'adresse' => $data['adresse'] ?: null,
                'actif' => true,
            ]);
        }

        // Représentants (colonnes: nom, email, telephone, adresse, actif)
        Representant::create([
            'nom' => 'Représentations Maritimes du Gabon',
            'email' => 'contact@rmg.ga',
            'telephone' => '+241 01 55 11 22',
            'adresse' => 'Port d\'Owendo',
            'actif' => true,
        ]);

        Representant::create([
            'nom' => 'Coastal Shipping Services',
            'email' => 'info@coastal.ga',
            'telephone' => '+241 01 55 33 44',
            'adresse' => 'Boulevard Maritime, Libreville',
            'actif' => true,
        ]);

        // Armateurs (colonnes: nom, email, telephone, adresse, actif)
        Armateur::create([
            'nom' => 'Maersk Line',
            'email' => 'gabon@maersk.com',
            'telephone' => '+241 01 66 11 22',
            'adresse' => 'Port d\'Owendo, Libreville',
            'actif' => true,
        ]);

        Armateur::create([
            'nom' => 'MSC - Mediterranean Shipping Company',
            'email' => 'gabon@msc.com',
            'telephone' => '+241 01 66 33 44',
            'adresse' => 'Zone Portuaire, Owendo',
            'actif' => true,
        ]);

        Armateur::create([
            'nom' => 'CMA CGM',
            'email' => 'libreville@cma-cgm.com',
            'telephone' => '+241 01 66 55 66',
            'adresse' => 'Port d\'Owendo',
            'actif' => true,
        ]);

        Armateur::create([
            'nom' => 'Grimaldi Lines',
            'email' => 'gabon@grimaldi.com',
            'telephone' => '+241 01 66 77 88',
            'adresse' => 'Terminal Roulier, Owendo',
            'actif' => true,
        ]);
    }
}
